name: Make Build Workflow

on:
  push: 
    branch:
      - make

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Build Environment
      run: sudo apt-get update && sudo apt-get install -y build-essential
      
    - name: Build Project
      run: make build
      
    - name: Install Project
      run: sudo make install

    - name: Clean Up
      run: make clean
